//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_BaiViet
    {
        public int maBaiViet { get; set; }
        [Display(Name = "Nội dung")]
        [MinLength(100, ErrorMessage = "Nội dung có ít nhất là 100 kí tự")]
        [Required(ErrorMessage = "Mời bạn nhập nội dung")]
        public string noiDung { get; set; }
        public string hinhBV { get; set; }
        [Required(ErrorMessage = "Mời bạn chọn ngày đăng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d/M/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Ngày đăng")]
        public Nullable<System.DateTime> ngayDang { get; set; }
        [Display(Name = "Tên bài viết")]
        [MinLength(4, ErrorMessage = "Tên bài viết có ít nhất là 4 kí tự")]
        [Required(ErrorMessage = "Mời bạn nhập tên bài viết")]
        public string tenBaiViet { get; set; }
        public Nullable<int> maLoai { get; set; }


        public virtual Tbl_LoaiBaiViet Tbl_LoaiBaiViet { get; set; }
    }
}
