//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HocPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_HocPhi()
        {
            this.Tbl_ChiTietHocPhi = new HashSet<Tbl_ChiTietHocPhi>();
        }
    
        public int maHP { get; set; }
        public string maThang { get; set; }
        public string maNamHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ChiTietHocPhi> Tbl_ChiTietHocPhi { get; set; }
        public virtual Tbl_NamHoc Tbl_NamHoc { get; set; }
        public virtual Tbl_ThangHoc Tbl_ThangHoc { get; set; }
    }
}
