//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InPhanCong
    {
        public string maGV { get; set; }
        public int Idphancong { get; set; }
        public string maLop { get; set; }
        public string maLoai { get; set; }
        public string maNamHoc { get; set; }
        public string tenLop { get; set; }
        public string tenNamHoc { get; set; }
        public string hoTen { get; set; }
        public Nullable<int> ngayBatDau { get; set; }
        public Nullable<int> ngayKetThuc { get; set; }
    }
}
