//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InLuong
    {
        public string hoTen { get; set; }
        public int soNgayLam { get; set; }
        public double soTien { get; set; }
        public string maGV { get; set; }
        public int maLuong { get; set; }
        public string tenThang { get; set; }
        public string maNamHoc { get; set; }
        public string tenNamHoc { get; set; }
    }
}
