//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HocPhi
    {
        public System.DateTime tenHocPhi { get; set; }
        public int soNgayHoc { get; set; }
        public string maHS { get; set; }
        public string soTien { get; set; }
        public string maLoai { get; set; }
    
        public virtual Tbl_HocSinh Tbl_HocSinh { get; set; }
        public virtual Tbl_LoaiLop Tbl_LoaiLop { get; set; }
    }
}
