//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_DanToc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_DanToc()
        {
            this.Tbl_GiaoVien = new HashSet<Tbl_GiaoVien>();
            this.Tbl_HocSinh = new HashSet<Tbl_HocSinh>();
        }

        public int maDanToc { get; set; }
        [Display(Name = "Tên dân tộc")]
        [MinLength(2, ErrorMessage = "Tên ít nhất 2 kí tự")]
        [Required(ErrorMessage = "Mời bạn nhập vào dữ liệu")]
        public string tenDanToc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_GiaoVien> Tbl_GiaoVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HocSinh> Tbl_HocSinh { get; set; }
    }
}
