//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_NgheNghiepCha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_NgheNghiepCha()
        {
            this.Tbl_HocSinh = new HashSet<Tbl_HocSinh>();
        }

        public int maNgheNghiepCha { get; set; }
        [Display(Name = "Tên nghề nghiệp cha")]
        [Required(ErrorMessage = "Mời bạn nhập dữ liệu")]
        public string tenNgheNghiepCha { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HocSinh> Tbl_HocSinh { get; set; }
    }
}
