//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InDanhSachHS
    {
        public int idInHS { get; set; }
        public string hoTenHS { get; set; }
        public string tenLop { get; set; }
        public string maLop { get; set; }
        public int maHS { get; set; }
        public string maNamHoc { get; set; }
        public string tenNamHoc { get; set; }
        public string gioiTinh { get; set; }
        public System.DateTime ngaySinh { get; set; }
        public string soDTNha { get; set; }
        public string diaChi { get; set; }
        public int idPhanLop { get; set; }
    }
}
