//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TienLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TienLuong()
        {
            this.Tbl_ChiTietLuong = new HashSet<Tbl_ChiTietLuong>();
        }
    
        public int maLuong { get; set; }
        public string maGV { get; set; }
        public string maThang { get; set; }
        public string maNamHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ChiTietLuong> Tbl_ChiTietLuong { get; set; }
        public virtual Tbl_GiaoVien Tbl_GiaoVien { get; set; }
        public virtual Tbl_NamHoc Tbl_NamHoc { get; set; }
        public virtual Tbl_ThangHoc Tbl_ThangHoc { get; set; }
    }
}
