//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_LopHoc()
        {
            this.Tbl_ChiTietDiemDanh = new HashSet<Tbl_ChiTietDiemDanh>();
            this.Tbl_ChiTietHocPhi = new HashSet<Tbl_ChiTietHocPhi>();
            this.Tbl_CTDiemDanhHS = new HashSet<Tbl_CTDiemDanhHS>();
            this.Tbl_PhanCong = new HashSet<Tbl_PhanCong>();
            this.Tbl_PhanLop = new HashSet<Tbl_PhanLop>();
        }

        public string maLop { get; set; }
        [Display(Name = "Tên lớp")]
        [MinLength(4, ErrorMessage = "Tên có ít nhất là 4 kí tự")]
        [Required(ErrorMessage = "Mời bạn nhập  tên lớp")]
        public string tenLop { get; set; }
        [Display(Name = "Số lượng")]
        [Range(10, Int32.MaxValue, ErrorMessage = "Nhập số và số lớn hơn 10 ")]
        [Required(ErrorMessage = "Mời bạn nhập vào dữ liệu")]
        public int soLuongHS { get; set; }
        public string maNamHoc { get; set; }
        public string maLoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ChiTietDiemDanh> Tbl_ChiTietDiemDanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ChiTietHocPhi> Tbl_ChiTietHocPhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CTDiemDanhHS> Tbl_CTDiemDanhHS { get; set; }
        public virtual Tbl_LoaiLop Tbl_LoaiLop { get; set; }
        public virtual Tbl_NamHoc Tbl_NamHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PhanCong> Tbl_PhanCong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PhanLop> Tbl_PhanLop { get; set; }
    }
}
