//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_NgheNghiep
    {
        public int maNgheNghiep { get; set; }
        [Display(Name = "Tên nghề nghiệp")]
        [Required(ErrorMessage = "Mời bạn nhập tên nghề nghiệp")]
        public string tenNgheNghiep { get; set; }

    }
}
