//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLMamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ChiTietLuong
    {
        public int maChiTietLuong { get; set; }
        public int maLuong { get; set; }
        public Nullable<int> soNgayLam { get; set; }
        public Nullable<double> soTien { get; set; }
        public string maGV { get; set; }
    
        public virtual Tbl_GiaoVien Tbl_GiaoVien { get; set; }
        public virtual Tbl_TienLuong Tbl_TienLuong { get; set; }
    }
}
